apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: e2e-tests
spec:
  image: ghcr.io/kubewarden/policy-server
  replicas: 1
  serviceAccountName: ~
  env:
  - name: KUBEWARDEN_LOG_LEVEL
    value: info
